#!/usr/bin/env python3
"""Build or verify manifest.json, catalog, gallery, and mapping integrity."""

from __future__ import annotations

import argparse
import hashlib
import json
import struct
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ICONS = ROOT / "icons"
MAPPING = ROOT / "mappings" / "aeris-icon-list.json"
MANIFEST = ROOT / "manifest.json"
CATALOG = ROOT / "docs" / "ICON_CATALOG.md"
GALLERY = ROOT / "docs" / "GALLERY.md"

PNG_SIGNATURE = b"\x89PNG\r\n\x1a\n"


def png_info(path: Path) -> dict:
    data = path.read_bytes()
    if len(data) < 29 or data[:8] != PNG_SIGNATURE or data[12:16] != b"IHDR":
        raise ValueError(f"Invalid PNG: {path}")
    width, height = struct.unpack(">II", data[16:24])
    bit_depth = data[24]
    color_type = data[25]
    return {
        "file": path.name,
        "width": width,
        "height": height,
        "bytes": len(data),
        "bit_depth": bit_depth,
        "color_type": color_type,
        "rgba": color_type == 6,
        "sha256": hashlib.sha256(data).hexdigest(),
    }


def collect() -> list[dict]:
    if not ICONS.is_dir():
        raise SystemExit("icons/ is missing")
    items = [png_info(p) for p in sorted(ICONS.glob("*.png"), key=lambda p: p.name.lower())]
    if not items:
        raise SystemExit("No PNG files in icons/")
    names = [x["file"] for x in items]
    if len(names) != len(set(names)):
        raise SystemExit("Duplicate icon filenames")
    not_rgba = [x["file"] for x in items if not x["rgba"]]
    if not_rgba:
        raise SystemExit(f"Icons are not PNG RGBA (color type 6): {not_rgba}")
    return items


def validate_mapping(icon_names: set[str]) -> dict:
    if not MAPPING.exists():
        return {}
    mapping = json.loads(MAPPING.read_text(encoding="utf-8"))
    if not isinstance(mapping, dict):
        raise SystemExit("Mapping must be a JSON object")
    missing = sorted({f"{value}.png" for value in mapping.values()} - icon_names)
    if missing:
        raise SystemExit(f"Mapping targets missing from icons/: {missing}")
    return mapping


def manifest_text(items: list[dict], mapping: dict) -> str:
    payload = {
        "project": "Weather Icons v2",
        "version": "2.0.0",
        "repository": "https://github.com/pgpaolo/weather-icons-v2",
        "license": "CC-BY-SA-4.0",
        "creator_attribution": "pgpaolo",
        "icon_count": len(items),
        "mapping_count": len(mapping),
        "icons": items,
    }
    return json.dumps(payload, indent=2) + "\n"


def catalog_text(items: list[dict], mapping: dict) -> str:
    lines = [
        "# Icon Catalog",
        "",
        "Generated by `tools/build_metadata.py`.",
        "",
        f"- PNG assets: **{len(items)}**",
        f"- Mapping entries: **{len(mapping)}**",
        "- PNG requirement: **RGBA / color type 6**",
        "",
        "| File | Dimensions | Bytes | SHA-256 |",
        "|---|---:|---:|---|",
    ]
    for item in items:
        lines.append(
            f"| `{item['file']}` | {item['width']}×{item['height']} | "
            f"{item['bytes']} | `{item['sha256']}` |"
        )
    lines.append("")
    return "\n".join(lines)


def gallery_text(items: list[dict]) -> str:
    lines = [
        "# Visual Gallery",
        "",
        "Generated by `tools/build_metadata.py`.",
        "",
        "<table>",
    ]
    columns = 5
    for start in range(0, len(items), columns):
        chunk = items[start:start + columns]
        lines.append("  <tr>")
        for item in chunk:
            name = item["file"]
            lines.append(
                f'    <td align="center"><img src="../icons/{name}" '
                f'width="110" height="110" alt="{name}"><br><code>{name}</code></td>'
            )
        for _ in range(columns - len(chunk)):
            lines.append("    <td></td>")
        lines.append("  </tr>")
    lines.extend(["</table>", ""])
    return "\n".join(lines)


def compare(path: Path, expected: str) -> bool:
    actual = path.read_text(encoding="utf-8") if path.exists() else None
    return actual == expected


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Verify generated files instead of writing them")
    args = parser.parse_args()

    items = collect()
    mapping = validate_mapping({x["file"] for x in items})

    outputs = {
        MANIFEST: manifest_text(items, mapping),
        CATALOG: catalog_text(items, mapping),
        GALLERY: gallery_text(items),
    }

    if args.check:
        stale = [str(path.relative_to(ROOT)) for path, text in outputs.items() if not compare(path, text)]
        if stale:
            print("Generated metadata is stale:", *stale, sep="\n- ", file=sys.stderr)
            return 1
        print(f"OK: {len(items)} PNG assets, {len(mapping)} mapping entries")
        return 0

    for path, text in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8", newline="\n")

    print(f"Generated metadata for {len(items)} PNG assets")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
